site:
  title: Antora Docs
  start_page: content:custom-integration:start.adoc
content:
  sources:
    - url: ./sl-content
      branches: main
ui:
  bundle:
    url: /Users/caseyparnis/Documents/docs-site/antora-ui-default/build/ui-bundle.zip
    snapshot: true