site: 
  title: Sendlane Docs
  url: https://help.caseyparnis.com
content:
  sources: 
  - url: https://github.com/caseyparnis/antora-component-template-master.git
ui:
  bundle:
    url: 'antora-ui-default-master/dist/_'
    snapshot: true